"""Load and use the resampled interpolated isochrone mass grid.

This module supports the on-disk format generated by
`bayesian-binary-masses/data/1. Isochrone grid.ipynb`:

- `gmag_grid.npy` : float64 array of shape (N,)
- `mass_interp_MH_<mh>.npy` : float64 array of shape (N,) for each MH value

The grid is 1D in magnitude for each discrete metallicity (MH), with optional
linear interpolation in MH to build a curve at an arbitrary MH.
"""

from __future__ import annotations

import os
import re
from typing import Dict, Optional, Tuple, Union

import numpy as np

_MASS_FILE_RE = re.compile(r"^mass_interp_MH_([+-]?\d+(?:\.\d+)?)\.npy$")


def default_interpolated_mass_data_dir() -> Optional[str]:
    """Return the repo-local default interpolated grid directory if it exists."""
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir))
    candidate = os.path.join(pkg_root, "data", "interpolated_mass_data")
    return candidate if os.path.isdir(candidate) else None


def _resolve_data_dir(data_dir: Optional[str]) -> str:
    if data_dir is None:
        data_dir = default_interpolated_mass_data_dir()
    if data_dir is None or not os.path.isdir(data_dir):
        raise FileNotFoundError(
            "Could not find interpolated mass grid directory. "
            "Pass `data_dir=...` (expected to contain `gmag_grid.npy`)."
        )
    return data_dir


def load_interpolated_mass_grid(
    data_dir: Optional[str] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load the full (MH, M_G) -> mass grid from `interpolated_mass_data/`.

    Returns
    -------
    absg_grid : ndarray, shape (N,)
        The G-magnitude grid (named `gmag_grid.npy` on disk).
    mh_grid : ndarray, shape (K,)
        Sorted list of MH values for which curves exist.
    mass_grid : ndarray, shape (K, N)
        Mass curve for each MH value on the shared absg_grid.
    """
    data_dir = _resolve_data_dir(data_dir)

    absg_grid = np.load(os.path.join(data_dir, "gmag_grid.npy"))
    absg_grid = np.asarray(absg_grid, dtype=float)
    if absg_grid.ndim != 1:
        raise ValueError(f"Expected 1D gmag_grid.npy, got shape={absg_grid.shape}")

    mh_to_path: Dict[float, str] = {}
    for fname in os.listdir(data_dir):
        m = _MASS_FILE_RE.match(fname)
        if not m:
            continue
        mh = float(m.group(1))
        mh_to_path[mh] = os.path.join(data_dir, fname)

    if not mh_to_path:
        raise FileNotFoundError(
            f"No mass curves found in {data_dir!r}. Expected files like `mass_interp_MH_-0.20.npy`."
        )

    mh_grid = np.array(sorted(mh_to_path.keys()), dtype=float)
    mass_grid = np.vstack([np.asarray(np.load(mh_to_path[mh]), dtype=float) for mh in mh_grid])

    if mass_grid.ndim != 2 or mass_grid.shape[1] != absg_grid.shape[0]:
        raise ValueError(
            "Mass grid shape mismatch: "
            f"mass_grid={mass_grid.shape} vs absg_grid={absg_grid.shape}"
        )

    return absg_grid, mh_grid, mass_grid


def load_interpolated_mass_curve(
    mh: float,
    data_dir: Optional[str] = None,
    *,
    mh_interpolation: str = "linear",
) -> Tuple[np.ndarray, np.ndarray]:
    """Return a single mass-vs-absg curve at MH=mh.

    Parameters
    ----------
    mh : float
        Target metallicity [M/H].
    data_dir : str, optional
        Directory containing `gmag_grid.npy` and `mass_interp_MH_*.npy`.
    mh_interpolation : {"linear","nearest"}
        How to build a curve for MH not exactly present in the grid.
        "linear" clips to the grid bounds; "nearest" snaps to closest MH.
    """
    absg_grid, mh_grid, mass_grid = load_interpolated_mass_grid(data_dir=data_dir)
    mh = float(mh)

    if mh_interpolation not in {"linear", "nearest"}:
        raise ValueError("mh_interpolation must be 'linear' or 'nearest'")

    if mh_interpolation == "nearest":
        idx = int(np.argmin(np.abs(mh_grid - mh)))
        return absg_grid, mass_grid[idx].copy()

    if mh_grid.size == 1:
        return absg_grid, mass_grid[0].copy()

    # Linear interpolation in MH, evaluated independently for each absg grid point.
    # (K, N) -> (N,) at fixed mh
    mass_curve = np.empty(absg_grid.shape[0], dtype=float)
    for j in range(absg_grid.shape[0]):
        mass_curve[j] = np.interp(
            mh,
            mh_grid,
            mass_grid[:, j],
            left=mass_grid[0, j],
            right=mass_grid[-1, j],
        )
    return absg_grid, mass_curve


def load_interpolated_isochrone_data(
    data_dir: Optional[str] = None,
    *,
    absg_key: str = "absg",
    mass_key: str = "mass",
    feh_key: str = "MH",
    return_table: bool = False,
) -> Union[dict, "Table"]:
    """Load the interpolated grid as a long-form isochrone table/dict.

    This expands the (K, N) grid into K*N points with columns:
    - absg_key : magnitude (M_G)
    - mass_key : mass (Msun)
    - feh_key  : metallicity (MH)
    """
    absg_grid, mh_grid, mass_grid = load_interpolated_mass_grid(data_dir=data_dir)
    n_mh = int(mh_grid.size)
    n_absg = int(absg_grid.size)

    data = {
        absg_key: np.tile(absg_grid, n_mh),
        mass_key: mass_grid.reshape(-1),
        feh_key: np.repeat(mh_grid, n_absg),
    }

    if not return_table:
        return data

    try:
        from astropy.table import Table  # type: ignore
    except Exception:
        return data
    return Table(data)

